#!/bin/sh

echo "-----Normalizing and updating production names"
psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/CharSym-Regular.ufo

echo "-----Updating glyph orders in Regular..."
psfsetglyphorder --header sort_design -i source/glyph_data.csv source/CharSym-Regular.ufo
